[Feature] 설정페이지 - 팀원소개 페이지 구현
MoodStation/MoodStation_iOS pull request #15
Opened 2022-03-13 14:19 UTC by Keeplo

### 해결안된부분  
* Layer를 이용해서 그라데이션 효과를 집어넣으면 계속 화면에 그려지는게 늦는 현상이 있습니다.. (조사중입니다 ㅠㅠ)
* UIImageView.image 에 png로 구현된 UIImage 넣으면 뒷 배경이 안보이는 현상 해결 못했습니다..

위에 언급한 부분은 진행하면서... 고쳐보겠습니다 ㅠㅠ

적용하신 Section 만들기 잘 배워서 적용해보았습니다 이상한 부분보이면 피드백 부탁드립니다.

2022-03-15 12:44 UTC, hogumachu requested changes
고생하셨습니다 ~~🔥

리뷰 확인해주시고 머지하시면 될 것 같슴다 !

2022-03-15 12:44 UTC, hogumachu commented on MoodStation/MoodStation/Home/HomeViewController.swift
> +final class HomeViewController: UIViewController, NavigationViewDelegate {
NavigationViewDelegate 따로 extension 으로 나눠도 좋을 것 같습니다 !

2022-03-15 12:44 UTC, hogumachu commented on MoodStation/MoodStation/Home/HomeViewController.swift
> +        homeView.snp.makeConstraints { make in
self 빠졌슴당

2022-03-15 12:44 UTC, hogumachu commented on MoodStation/MoodStation/Home/HomeViewModel.swift
>      func headerData(at index: Int) -> Date {
네이밍을 조금 다르게 하는 건 어떨까요 ?
Data 라는 것보다 HeaderModel ? 같은 느낌으로요 !

2022-03-15 12:44 UTC, hogumachu commented on MoodStation/MoodStation/Home/RecordListHeaderView.swift
>      static let recordDateFormatter = DateFormatter().then {
View 가 DateFormatter 를 가지고 있는 것보다 ViewModel 같은 애들이 갖고 있는 것이 더 좋아보여요 !

2022-03-15 12:44 UTC, hogumachu commented on MoodStation/MoodStation/Settings/ContactUs/ContactViewController.swift
> +final class ContactView: UIView {
파일 따로 나눠도 좋을 것 같습니다 !

2022-03-15 12:44 UTC, hogumachu commented on MoodStation/MoodStation/Home/HomeView.swift
> +            $0.register(RecordListCell.self, forCellReuseIdentifier: RecordListCell.className)
기존에 사용하는 `$0.register(RecordListCell.self)` 사용해도 좋을 것 같습니다 !

2022-03-15 12:44 UTC, hogumachu commented on MoodStation/MoodStation/Settings/UserTableViewCell.swift
> +        gradientView.addSubview(self.userImageView)
self 가 빠졌습니다 !

2022-03-15 12:49 UTC, Keeplo commented on MoodStation/MoodStation/Home/HomeViewModel.swift
>      func headerData(at index: Int) -> Date {
조금 고민해보고 수정하겠습니다!

급 별개인데.. 혹시 위 코드 42번 부분에 safe:  형태로 구성하시던데 처음봐가지고요.. 혹시 관련 부분 공부하기에 어떤 키워드로 찾아보면 좋을까요?

2022-03-15 12:52 UTC, Keeplo commented on MoodStation/MoodStation/Home/HomeViewModel.swift
>      func headerData(at index: Int) -> Date {
cellMode() 과 일관성있게 말씀하신 headerModel이 적절할것 같아요.. ㅎ

2022-03-15 12:55 UTC, hogumachu commented on MoodStation/MoodStation/Home/HomeViewModel.swift
>      func headerData(at index: Int) -> Date {
배열에서 index 범위를 벗어나게 되면 nil 을 리턴하는 옵셔널 입니다!
swift subscript 를 검색하시면 아마 찾아볼 수 있을 것 같슴다 !

2022-03-15 12:57 UTC, hogumachu commented on MoodStation/MoodStation/Home/HomeViewModel.swift
>      func headerData(at index: Int) -> Date {
뭔가 Data 라고 하면 뭔가 디코딩 인코딩 시켜야할 것 같아서 저는 잘 안쓰고 있습니다 ㅋㅋ

저는 대부분 네트워크 연관된 곳에서 사용하고 있슴당

2022-03-15 13:24 UTC, Keeplo commented on MoodStation/MoodStation/Home/RecordListHeaderView.swift
>      static let recordDateFormatter = DateFormatter().then {
configure 할때만 사용하는 부분이라서 요렇게 구현을 해보았는데..
데이터를 그리기위한 작업의 일부로 볼 수 있지 않을까요? (이런식으로 하는 코드를 몇번 봐서 요렇게 해봤습니다!)

RecordListCell 에도 동일하게 했었는데 이 경우만 말씀해주신걸까요??

cell과 이 부분이 공유노선도에서도 재사용할 수 도 있다고 생각해서 
다른 객체(ViewModel)에 의존하거나 매번 생성하는것 보다 static으로 하면 어떨까 하고 구현해보았습니다..

2022-03-15 13:27 UTC, Keeplo commented on MoodStation/MoodStation/Home/HomeViewModel.swift
>      func headerData(at index: Int) -> Date {
> 뭔가 Data 라고 하면 뭔가 디코딩 인코딩 시켜야할 것 같아서 저는 잘 안쓰고 있습니다 ㅋㅋ
> 
> 저는 대부분 네트워크 연관된 곳에서 사용하고 있슴당

그러네요 ㅎㅎ Data 타입도 있는데.. 확실히 말씀하신 부분이 맞는것 같아요ㅎㅎㅎ

2022-03-15 13:28 UTC, Keeplo commented on MoodStation/MoodStation/Home/RecordListHeaderView.swift
>      static let recordDateFormatter = DateFormatter().then {
포메터 처리를 ViewModel이나 ViewController에서 많이 하나요?

2022-03-15 13:32 UTC, hogumachu commented on MoodStation/MoodStation/Home/RecordListHeaderView.swift
>      static let recordDateFormatter = DateFormatter().then {
cell 은 누군가가 계속해서 그려주는 거라고 생각합니다.

configure 를 통해서 누군가 그려줘야하는데
기존 코드도 HomeViewModel 에게 cellModel 을 받아서 진행을 하는데
이것 자체가 이미 의존하는 것이라 이 cellModel 을 받을 때 Date 를 받는 것이 아닌 Date 를 이미 DateFormatter 로 가공한 값을 받는 것이 좋다고 생각합니다.

결국 ViewModel 이 로직을 가지고 있는 것이라 ViewController - ViewModel 에 대한 연결은 어쩔 수 없이 가져야 한다고 생각합니다.

2022-03-15 13:38 UTC, hogumachu commented on MoodStation/MoodStation/Home/RecordListHeaderView.swift
>      static let recordDateFormatter = DateFormatter().then {
> 포메터 처리를 ViewModel이나 ViewController에서 많이 하나요?

ViewModel 에서 하거나 또는 뭔가 날짜에 관한 것을 처리하는 일이 많다면 Manager 하나를 생성해도 좋을 것 같습니다 !

2022-03-15 13:48 UTC, hogumachu commented on MoodStation/MoodStation/Home/RecordListHeaderView.swift
>      static let recordDateFormatter = DateFormatter().then {
코멘트 테스트

2022-03-16 14:56 UTC, merged

2022-03-16 14:57 UTC, hogumachu commented
고생하셨습니다 !!!! 🙌🙌🙌🙌